version: "3.2"
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb-container
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}  
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - ${DB_MANAGE_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
    links: 
        - mongodb:mongodb
    restart: unless-stopped
  nodejs:
     image: node:latest
     container_name: node-container
     restart: always
     env_file:
      - .env
     depends_on: 
      - mongodb
     ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
     volumes:
      - .:/usr/src/compass_backend
     working_dir: /usr/src/compass_backend 
     command: yarn start
     logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


volumes:
  mongodb-vol: